version: "3.9"
services:
  flask_server:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db

  telegram_bot:
    build:
      context: ./telegram_bot
    env_file: .env
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ZX060688
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./credentials.json:/app/credentials.json
    ports:
      - "5432:5432"

volumes:
  pgdata:
